"""change rule to array

Revision ID: 19af984e7d8f
Revises: 440068a06e4f
Create Date: 2025-02-04 13:47:12.682001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19af984e7d8f'
down_revision: Union[str, None] = '440068a06e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rules', sa.ARRAY(sa.String()), nullable=False))
    op.drop_column('users', 'rule')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rule', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'rules')
    # ### end Alembic commands ###
