"""change u to o

Revision ID: 2008cdefe32e
Revises: 19af984e7d8f
Create Date: 2025-02-04 13:56:31.037751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2008cdefe32e'
down_revision: Union[str, None] = '19af984e7d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', sa.ARRAY(sa.String()), nullable=False))
    op.drop_column('users', 'rules')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rules', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###
