"""add join_date and rule columns to users

Revision ID: 440068a06e4f
Revises: 90d33e8b2eee
Create Date: 2025-02-04 13:40:53.772846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '440068a06e4f'
down_revision: Union[str, None] = '90d33e8b2eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('join_date', sa.Date(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('rule', sa.String(), nullable=False))
    op.drop_index('ix_users_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_column('users', 'rule')
    op.drop_column('users', 'join_date')
    # ### end Alembic commands ###
